[package]
name = "demangle-gnuv2-py"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "demangle_gnuv2"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.24.0"
demangle-gnuv2 = { path = ".." }
